name: install_internetarchive
on:
  pull_request:
  push:
jobs:
  install_internetarchive:
    runs-on: ubuntu-latest
    steps:
      - run: pip install internetarchive
  install_tqdm_and_then_internetarchive:
    runs-on: ubuntu-latest
    steps:
      - run: pip install tqdm  # This line is REQUIRED
      - run: pip install internetarchive
