name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      - run: pip install --upgrade pip wheel
      - run: pip install .[all]
      - run: black --check . || true
      - run: flake8 .  # See setup.cfg for configuration
      - run: pip install -r pex-requirements.txt -r tests/requirements.txt
      - run: safety check
