name: tox
on: [push, pull_request]
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1  # Avoid timeout errors
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10', '3.11', 'pypy-3.7', 'pypy-3.8', 'pypy-3.9']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - run: pip install tox
      - run: tox -e py
