name: tox
on: [push, pull_request]
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1  # Avoid timeout errors
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', 'pypy-3.9', 'pypy-3.10']
        envname: ['py']  # To allow testing more special configurations below
        include:
          - { python: '3.12', envname: 'py312ujson' }  # With optional ujson dependency
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - run: pip install tox
      - run: tox -e ${{ matrix.envname }}
